# fly.toml app configuration file generated for actionplusmetz on 2026-02-08T21:01:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'actionplusmetz'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8080"

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
